import type { Metadata } from 'next'
import './globals.css'

import { Sidebar } from '@/components/SideBar/Sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="font-roboto">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Agbalumo&display=swap" rel="stylesheet"></link>
      </head>
      <body className="flex">
        <div className='w-44'>
          <Sidebar/>
        </div>
        {children}
      </body>
    </html>
  )
}
